### ISSUE TITLE
Write up how to estimate points in our Sprint Planning wiki 

### ISSUE THREAD

**Issue by dlebauer** [az-digitalag/organization#226]
Also when to ask for help

Don't want to map point to time but ....

* 1 ~ 1/2 day
* 2 ~ 1-2 days
* 5 ~ 1 week ... most issues w/ 5 points might be an epic unless steps are clearly enumerated

Full sprint total should be ~13-15

the value of an issue depends on who is doing it so that everyone should be able to target the same number of points. Otherwise someone w/ 20 y experience should have at least 5x points, which is silly and demoralizing for those with less experience.

**Comment by Chris-Schnaufer** [comment]
I think that we should also note that while this diverges from the standard, it's an approach that's common.

**Comment by KristinaRiemer** [comment]
This should go on [the terminology OSF page](https://osf.io/tzmhp/wiki/Agile/).

**Comment by dlebauer** [comment]
Updated: https://osf.io/tzmhp/wiki/Agile/

**Comment by Chris-Schnaufer** [comment]
>We have decided to use this non-standard approach because it helps with estimating for individuals; the alternative textbook approach is that estimates are estimated per task and independent of the assignee.
Otherwise someone w/ 20 y experience should have at least 5x points, which is silly and demoralizing for those with less experience.  

I am updating the above text to reflect the use of points for effort and not hours. See the section titled [What do Story Points represent?](https://medium.com/serious-scrum/12-common-mistakes-made-when-using-story-points-f0bb9212d2f7) and from [Agile Alliance](https://www.agilealliance.org/glossary/points-estimates-in/#q=~(infinite~false~filters~(postType~(~'page~'post~'aa_book~'aa_event_session~'aa_experience_report~'aa_glossary~'aa_research_paper~'aa_video)~tags~(~'story*20points))~searchTerm~'~sort~false~sortDirection~'asc~page~1))
